[package]
name = "rirc_slack"
version = "0.1.0"
authors = ["tux3 <barrdetwix@gmail.com>"]

[dependencies]
rirc_server = { path = "../rirc_server" }
reqwest = "0.8.5"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
lazy_static = "1.0.0"
hyper = "0.11"
futures = "0.1.18"
